spring:
  application:
    name: payments

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 40MB

  config:
    import:
      - "classpath:/portone-key.yaml"
      - "classpath:/esp32-uart.yaml"
      - "classpath:/database.yaml"